config/routes.rb
Rails.application.routes.draw do
  root 'tasks#index'
  get '/tasks', to: 'tasks#index'
  post 'tasks', to: 'tasks#create'
  get 'tasks/new', to: 'tasks#new'
  get 'tasks/:id', to: 'tasks#show', as: :task

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
  after_initialize :set_defaults

  def set_defaults
    completed = 'false'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to task_path(@task)
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_controlle_helper.rb
module TasksControlleHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with model: task do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <br>

  <div>
    <%= f.label :details %>
    <%= f.text_field :details %>
  </div>

  <br>
  
  <%= f.submit %>
<% end %>

app/views/tasks/index.html.erb
<h1>My Tasks</h1>
<ul>
  <% @tasks.each do |task| %>
    <%if task.completed %>
      <div><input type="checkbox" checked><%= link_to task.title, task_path(task) %></div>
    <%else %>
      <div><input type="checkbox"><%= link_to task.title, task_path(task) %></div>
    <% end %>
  <% end %>
</ul>

<%= link_to "+ Add new Task", tasks_new_path %>

app/views/tasks/new.html.erb
<%= render "form", task: @task %>

app/views/tasks/show.html.erb
<div><%= @task.title%></div>
<div><%= @task.details%></div>
<%if @task.completed %>
  <p>This task is completed</p>
<%else %>
  <p>This task is not completed yet</p>
<% end %>

<%= link_to "Go Back", tasks_path %>